# Generated by Django 6.0.6 on 2026-07-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
