# Generated by Django 6.0.6 on 2026-07-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
