# Generated by Django 6.0.6 on 2026-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover_pics'),
        ),
    ]
